name: Auto Deploy Project When Push Main Branch
on:
  push:
    branches:
      - gh-pages
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Deploy
        uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.GH_TOKEN }}
          deploy-branch: main
